#!/usr/bin/env bash
#Write a Bash script that displays the content of the file /etc/passwd, using the while 

IFS=':'
while read -r user pass uid gid username_f homedir loginshell; do
      echo "The user $user is part of the $gid gang, lives in $homedir and rides $loginshell. $uid's place is protected by the passcode $pass, more i		nfo about the user here: $username_f"
done </etc/passwd
