#!/usr/bin/env bash
#dsplay  4_bad_luck_8_is_your_chance

i=0

while [ $i -lt 10 ]; do
	if [ $i -eq 3 ]; then
		echo "bad luck"
	elif [ $i -eq 7 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	i=$((i+1))
done
